### ISSUE TITLE
Failed to save musical interval to AnkiDroid

### ISSUE THREAD

**Issue by Andrej-Adamenko** [lwp-emelnik/musicintervals2anki#1]
![Screenshot_20201221-054657_MusicIntervals2Anki.jpg](https://user-images.githubusercontent.com/70955223/102737648-ad5e1180-4350-11eb-88f3-97fa63f52575.jpg)

@lwp-emelnik 
1. Find out how to fix the actual problem
2. Add more details in the error message if possible 
3. Add unit test(s) that fail, before writing or changing any code

**Comment by lwp-emelnik** [comment]
Possible cause fixed and deployed to google play, updated version should be available soon
