### ISSUE TITLE
Fix autocomplete for instrument input

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#100]
Steps to reproduce:
1. Add a note with `instrument` field value "bass guitar";
2. Add a note with `instrument` field value "guitar";
3. While trying to add a third note, start typing "guitar" to the `instrument` field.

Expected result: 
"guitar" option is suggested (along with bass guitar).

Actual result:
Only "bass guitar" option is suggested.

**Comment by lwp-ygavrilenko** [comment]
The options for the input autocomplete should be based on the values from the saved notes.

**Comment by lwp-vinokurova** [comment]
Tested:
- autocomplete if instrument was added from MI2A
- autocomplete is instrument was added from AnkieDroid
