### ISSUE TITLE
Testing (1.7.0)

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#103]
1. Capture video and/or sound directly in the app (#24):
- skippable countdown;
- movable overlay;
- captured file is added to the list on stop recording action.
2. Add an option to automatically delete audio and video files upon insertion to Anki (#86):
- setting options;
- dialog options.
3. Update model to support music intervals with extended first note duration (#87):
- new field usage, configuration
- empty value counts as default value (1);
- different formats of the same value are treated as equal (i. e. "1" and "1.0", etc)

**Comment by lwp-vinokurova** [comment]
Found issues in Capture video and/or sound directly in the app (#24):

1. [bug] whole popup overlay should be movable (now buttons are not movable)
2. [improvement] when user record audio in another app - on "close" button in movable popup return user to our app
