### ISSUE TITLE
Fix default model updating

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#111]
There seem to be sync issues with adding new fields during the default model updating procedure. 
Additionally, an outdated model dialog prompt should be more informative, providing a third option that would disable default model usage.

**Comment by lwp-vinokurova** [comment]
Tested:
- default model updation after fields in MI2A were added
- model update after card layout was changed
- model update after cards we added/deleted
- user is proposed to use custom model
- user can not continue using app until he selects update default/use custom model option
