### ISSUE TITLE
Corrupt captured audio quality

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#123]
Occasionally the sound capture feature may produce artifacts. This must be investigated.
 
 

https://user-images.githubusercontent.com/77337235/121354410-85cb2780-c937-11eb-8097-18efeef02d4c.mp4

![image](https://user-images.githubusercontent.com/77337235/121354347-777d0b80-c937-11eb-86c2-ced62d20f92f.png)

**Comment by lwp-ygavrilenko** [comment]
Could not find a stable way of reproducing the issue. Nevertheless, several improvements have been made: 
- moved to third-party audio converter (https://github.com/lincollincol/PCM-Decoder)
- fixed releasing resources used for audio playback

If the issue persists, another possible solution could be to create `MediaPlayer` objects on-demand, separately for each particular playback. The dev [docs](https://developer.android.com/reference/android/media/MediaPlayer#state-diagram) are rather vague about this:
> It is also recommended that once a MediaPlayer object is no longer being used, call release() immediately so that resources used by the internal player engine associated with the MediaPlayer object can be released immediately.

**Comment by lwp-vinokurova** [comment]
Tested 2021-07-26
Seems that issue with audio corrupting is still reproduced. 
@lwp-ygavrilenko Check please, audio during capturing differs from the audio while playing it.

**Comment by lwp-vinokurova** [comment]
Tested 2021-07-28

For audio capturing Perfect Ear was used:
- while capturing from MI2A some noises were present
- while capturing from another app some noises were present

For audio capturing another app Real Piano was used
- while capturing from MI2A noises were absent
- while capturing from another app noises were absent

Seems that it is an issue connected with capturing audio from the perfect ear app
