### ISSUE TITLE
Add cancel option to duplicate adding dialog

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#125]

**Comment by lwp-ygavrilenko** [comment]
![image](https://user-images.githubusercontent.com/77337235/121354719-d2aefe00-c937-11eb-9add-696c69cda7dd.png)

**Comment by lwp-vinokurova** [comment]
Tested:
- cancel adding one duplicated audio
- cancel adding several duplicated audio files 
- also checked other options (mark, replace, add anyway)
