### ISSUE TITLE
Add an option to clear recorded sounds upon capture initiation

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#126]
When the user clicks 'Capture' while there are still unadded captured files selected, a dialog prompt should be shown, asking whether the list should be cleared or new files should be appended to the existing ones.

**Comment by lwp-vinokurova** [comment]
Tested:
- a dialog prompt is shown when there are already unuploaded captured filed (at least one)
- a dialog prom is not displayed if captured audio is already uploaded
- a dialog prom is not displayed if audio was selected from the phone
