### ISSUE TITLE
Warn about adding interval that already exists

### ISSUE THREAD

**Issue by Andrej-Adamenko** [lwp-emelnik/musicintervals2anki#13]
On adding a new interval to Anki first check if an interval with the exact same parameters already exists in Anki. If it does, warn and give the user the following options:
- to add anyway;
- to replace the existing one with the new one;
- to mark the existing interval instead of adding the new one;

**Comment by Andrej-Adamenko** [comment]
in the case of replacing the interval I believe user should run "check media" command in Anki to find and delete the orphaned old sound file.

**Comment by lwp-ygavrilenko** [comment]
The option to replace the existing interval should only be displayed in case of a single duplicate.
Upon forcefully adding a duplicate, it should be marked with a special tag. The settings should include the options to disable this behavior and customize the special tag. The integrity check (#31) should also employ this behavior.

**Comment by Andrej-Adamenko** [comment]
Marking the duplicates with the special tag should be done even if the new interval was not added.

**Comment by Andrej-Adamenko** [comment]
> in the case of replacing the interval I believe user should run "check media" command in Anki to find and delete the orphaned old sound file.

so the app should remind the user about it when replacing an interval.
