### ISSUE TITLE
Error notifications should not create a queue to be displayed

### ISSUE THREAD

**Issue by lwp-vinokurova** [lwp-emelnik/musicintervals2anki#134]
**Steps to reproduce**

1. Miss a mandatory field
2. Press "Add to Ankidroid" button several times

**Actual Result:** Several the same error notifications will be displayed after each other.
Each notification is displayed for 3 seconds. In such a case each notification will be displayed for 3 seconds (3+3+3+3...)
**Expected Result:** We should cancel displaying the previous notification (if they are duplicated) and display new one

**Comment by Andrej-Adamenko** [comment]
In this specific case, yes, it is better to cancel the previous notification. But what if the previous notification contained some important information which the user had not time to see. Is it possible to move the previous notifications up on the screen and show them all at the same time instead of delaying them?

**Comment by lwp-ygavrilenko** [comment]
> In this specific case, yes, it is better to cancel the previous notification. But what if the previous notification contained some important information which the user had not time to see. Is it possible to move the previous notifications up on the screen and show them all at the same time instead of delaying them?

The current implementation doesn't allow for displaying more than one message at once (using built-in `Toast` widget). 
Besides, I don't think in the current version of the app there are ways to initiate consecutive displaying of different messages without performing some kind of action in between, which would allow noticing the first message. 
Implementing the proposed feature would require either moving to a different message displaying solution or developing our own. Please let me know if you think this needs to be done.

**Comment by lwp-vinokurova** [comment]
Tested:
- if notification is unique - it will be displayed in a queue (one replace another in a several seconds)
- if notification is duplicated - it is not displayed
