### ISSUE TITLE
Unison is not ascending nor descending. 

### ISSUE THREAD

**Issue by Andrej-Adamenko** [lwp-emelnik/musicintervals2anki#138]
So the app should ignore the field content on read and clear it on write. 

Unison should be "linkable" with  ascending or descending minor seconds.

Consistency check should clear the direction field for unison intervals.

**Comment by lwp-vinokurova** [comment]
Cases for unison linking were tested in https://github.com/lwp-emelnik/musicintervals2anki/issues/188
