### ISSUE TITLE
Some files are referenced by cards, but were not found in the media folder

### ISSUE THREAD

**Issue by Andrej-Adamenko** [lwp-emelnik/musicintervals2anki#14]
The following files are referenced by cards, but were not found in the media folder:
Missing: ⁨music_interval_1614394007.m4a⁩
Missing: ⁨music_interval_1614395144.m4a⁩
Missing: ⁨music_interval_1614396262.m4a⁩
Missing: ⁨music_interval_1614396317.m4a⁩
Missing: ⁨music_interval_1614396574.m4a⁩
Missing: ⁨music_interval_1614396588.m4a⁩

Steps to reproduce:
1. Click "Tools->Check Media" in Anki for Desktop.
2.
![image](https://user-images.githubusercontent.com/70955223/109385595-a843b280-78fd-11eb-8d25-2673d9357875.png)

**Comment by Andrej-Adamenko** [comment]
I discovered that the problem is reproducible on in Desktop version of Anki.

**Comment by lwp-ygavrilenko** [comment]
Could you please try to do the following and see if it resolves the issue:
1. On the AnkiDroid app, click the button with three vertical dots on it (upper-right corner)
2. Click "Check media"
3. Click sync button

**Comment by Andrej-Adamenko** [comment]
it worked, but the problem should be fixed anyway

**Comment by lwp-ygavrilenko** [comment]
The next app release will include a rework of the files adding logic to Anki collection.
