### ISSUE TITLE
Handle the case of audio capturing initiation (button pressed) when capturing is already active (overlay visible)

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#169]

**Comment by lwp-ygavrilenko** [comment]
The same goes for other actions that modify the filenames list: "select files" and "add to Anki"

**Comment by lwp-vinokurova** [comment]
Tested:
 - capture audio popup is closed by "Select file", "Capture audio", "View All" "Add to AnkiDroid" buttons
 - tested cases when there is no captured audio files, capturing is in progress and audio is already captured
 -  capture audio popup is still closed by its "Close"button
