### ISSUE TITLE
Count different harmonic interval notations as duplicates

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#188]
e. g. C2, harmonic. ascending, Maj2 and D2, harmonic, descending, Maj2

**Comment by lwp-ygavrilenko** [comment]
On top of being counted as duplicates, such relations should be considered when filling links. For example, C2, harmonic. ascending, Maj2 should be linked with D2, harmonic, descending, min3.

**Comment by lwp-ygavrilenko** [comment]
Let's write an array of available `start_note` values sorted first by octave then by note (C1, C#1, D1, D#1, E1, F1, F#1, G1, G#1, A1, A#1, B1, C2, C#2, ... , A#6,  B6) as _NOTE = (A[0], A[1], ..., A[n])_

Let's also write an array of available `interval` field values sorted by the distance in semitones (Uni, min2, Maj2, min3, Maj3, P4, Tri, P5, min6, Maj6, min7, Maj7, Oct) as _INT = (B[0], B[1], ..., B[m])_

Available `ascending_descending` (direction) values: _DIR = {ascending, descending}_. For a certain direction value of _dir ∈ DIR_ let's label the opposite direction as _dir'_. (i. e. _dir' = ascending_ if _dir = descending_, otherwise _descending_)

For simplicity, let's assume the music interval is only identified by the fields `start_note`, `ascending_descending`, `interval`. We can label a particular music interval with a tuple of (note ∈ NOTE, interval ∈ INT, direction ∈ DIR)

For  each _i ∈ [0, n)_, _j ∈ (0, m)_, and _dir ∈ DIR_, assuming the music interval is harmonic, the following rules must apply:
_(NOTE[i], INT[j], dir)_`.sound.larger` = _(NOTE[i], INT[j + 1], dir)_`.sound` OR (_NOTE[i + j + 1] , INT[i + 1], dir')_`.sound`
_(NOTE[i], INT[j], dir)_`.sound.larger.alt` = _(NOTE[i + j], INT[j + 1] dir')_`.sound` OR _(NOTE[i - 1], INT[j + 1], dir)_`.sound`
_(NOTE[i], INT[j], dir)_`.sound.smaller` = _(NOTE[i], INT[j - 1], dir)_`.sound` OR (_NOTE[i + j - 1] , INT[i - 1], dir')_`.sound`
_(NOTE[i], INT[j], dir)_`.sound.smaller.alt` = _(NOTE[i + j], INT[j - 1] dir')_`.sound` OR _(NOTE[i + 1], INT[j - 1], dir)_`.sound`

**Comment by lwp-vinokurova** [comment]
Tested. **Passed cases**:
- all described cases were passed for **harmonic intervals** with the following data
(NOTE[2], INT[2], 1).sound.larger = (NOTE[2], INT[3], 1).sound OR (NOTE[5], INT[3], -1).sound
(NOTE[2], INT[2], 1).sound.larger.alt = (NOTE[4], INT[3], -1).sound OR (NOTE[1], INT[3], 1).sound
(NOTE[2], INT[2], 1).sound.smaller = (NOTE[2], INT[1], 1).sound OR (NOTE[3] , INT[1], -1).sound
(NOTE[2], INT[2], 1).sound.smaller.alt = (NOTE[4], INT[1], -1).sound OR (NOTE[3], INT[1], 1).sound
- case for unison
(NOTE[i], INT[0], dir).sound.larger = (NOTE[i], INT[1], dir).sound OR (NOTE[i + dir] , INT[1], -dir).sound


**Failed cases:**
- case for unison
(NOTE[i], INT[0], dir).sound.larger = (NOTE[i], INT[1], dir).sound OR (NOTE[i + dir] , INT[1], -dir).sound
- all cases for melodic intervals (unison)

@lwp-ygavrilenko Check it please

**Comment by lwp-ygavrilenko** [comment]
Updated melodic unison alternative link rule please check @lwp-vinokurova
The issue with harmonic & melodic unisone alternative links is being investigated and will be fixed shortly

**Comment by lwp-vinokurova** [comment]
**Examples of test cases with real data:** 

1. Created in MI2A:
   Interval1: (D2, ascending, harmonic, Maj2)
   Interval2: (D2, ascending, harmonic, min2)
   Checked in AnkiDroid:
   Interval1.sound_larger = Interval2.sound 
   Interval2.sound_smaller = Interval1.sound
   Created in MI2A:
   Interval3: (F2, descending, harmonic,min3)
   Checked in AnkiDroid:
   Interval1.sound_larger = Interval3.sound 
   Interval2.sound_smaller = Interval1.sound
   Interval3.sound_smaller_alt = Interval1.sound 
 
   Interval2.sound = Interval3.sound
   Link for Interval1.sound_larger was updated from Interval1.sound to Interval3.sound after adding new interval3.sound
   
   
2. Created in MI2A:
   Interval1: (D2, descending, harmonic, Maj2)
   Interval2: (С2, ascending, harmonic, min3)
   Checked in AnkiDroid:
   Interval1.sound_larger_alt = Interval2.sound 
   Interval2.sound_smaller = Interval1.sound
   Created in MI2A:
   Interval3: (D#2, descending, harmonic,min3)
   Checked in AnkiDroid:
   Interval1.sound_larger_alt = Interval3.sound 
   Interval2.sound_smaller = Interval1.sound
   Interval3.sound_smaller_alt = Interval1.sound
   
   Interval2.sound = Interval3.sound
   Link for Interval1.sound_larger was updated from Interval1.sound to Interval3.sound after adding new interval3.sound
   
3. Case for unison:
   (NOTE[3], INT[0], 1.sound.larger = (NOTE[3], INT[1], 1).sound OR (NOTE[4] , INT[1], -1).sound
   Created in MI2A:
   Interval1: (D#3, ascending, harmonic, Uni)
   Interval2: (D#3, ascending, harmonic, min2)
   Checked in AnkiDroid:
   Interval1.sound_larger = Interval2.sound 
   Interval2.sound_smaller = Interval1.sound
   Created in MI2A:
   Interval3: (D#3, descending, harmonic, Uni)
   Checked in AnkiDroid:
   Interval1.sound_larger_alt = Interval3.sound 
   Interval2.sound_smaller = Interval1.sound
   Interval3.sound_smaller_alt = Interval1.sound

   Interval2.sound = Interval3.sound
   Link for Interval1.sound_larger was updated from Interval1.sound to Interval3.sound after adding new interval3.sound

**Found the following issue with Unison:**
The backlink does not change for interval1 after adding new Interval3

   Created in MI2A:
   Interval1: (D2, ascending, harmonic, Uni)
   Interval2: (C#2, ascending, harmonic, min2)
   Checked in AnkiDroid:
   Interval1.sound_larger_= Interval2.sound 
   Interval2.sound_smaller = Interval1.sound
   Created in MI2A:
   Interval3 (D2, descending, harmonic, min2)
   Checked in AnkiDroid:

   **Actual Result:**
   Interval1.sound_larger_alt = Interval2.sound 
   Interval2.sound_smaller = Interval1.sound
   Interval3.sound_smaller_alt = Interval1.sound
   **Expected Result:** 
   Interval1.sound_larger_alt = Interval3.sound 
   Interval2.sound_smaller = Interval1.sound
   Interval3.sound_smaller_alt = Interval1.sound

**Comment by lwp-vinokurova** [comment]
**- Tested fix for the Issue "The backlink does not change for interval1 after adding new Interval3"** with the same data as specified above - issue is not reproduced now,
Link for Interval1.sound_larger was updated from Interval1.sound to Interval3.sound after adding new interval3.sound

**- Tested additional case for melodic interval**
Created in MI2A:
Interval1: (D3, ascending, melodic, Uni)
Interval2: (D3, descending, melodic, min2)
Checked in AnkiDroid:
Interval1.sound_larger_alt= Interval2.sound
Interval2.sound_smaller = Interval1.sound
