### ISSUE TITLE
Make tempo field optional

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#189]
The field should also be ignored while "linking" notes (both during integrity check and after adding), unless more than one candidate is suitable, in which case the nearest value should be chosen.

**Comment by lwp-vinokurova** [comment]
Tested: 
- tempo fields is optional while creating interval from MI2A
- error with tempo field is not displayed on integrity check if interval was added from AnkiDroid without tempo
- tempo field is ignored while "linking" notes
- if more than one candidate is suitable, in this case the nearest value is chosen
