### ISSUE TITLE
App is opened with a delay if Cancel button was pressed in "Capture audio" popup on the homepage

### ISSUE THREAD

**Issue by lwp-vinokurova** [lwp-emelnik/musicintervals2anki#195]
After implementation https://github.com/lwp-emelnik/musicintervals2anki/issues/132 the following issue appeared - app is opened with a delay if Cancel button was pressed in "Capture audio" popup on the homepage

STR:
1. Press Capture audio button to open popup 
2. Collapse the app and go to the homescreen
3. Press "Close" button

Actual Result: MI2A app is opened with a big delay if "Cancel" was pressed on the home screen.
Expected Result: MI2A should be opened immediately after "Cancel" button is pressed.

Additional Information: if collapse the app/open another and press Cancel - MI2A is opened quickly without a delay

**Comment by lwp-vinokurova** [comment]
https://user-images.githubusercontent.com/85628357/125978165-9a4d0f59-de38-4118-a589-f3522de0ab90.mp4

**Comment by lwp-ygavrilenko** [comment]
Apparently, it's not a bug - it is a feature that does not allow Services or BroadcastReceivers to launch activities for up to 5 seconds after the home button is pressed (https://issuetracker.google.com/issues/36910222).
