### ISSUE TITLE
Options in "Automatic files deletion" popup should be located in the same way in both horizontal and vertical orientations 

### ISSUE THREAD

**Issue by lwp-vinokurova** [lwp-emelnik/musicintervals2anki#198]
**Actual Result:** 
Sequence in vertical orientation: Delete all added, Delete recorded only, Do nothing
Sequence in horizontal orientation: Do nothing, Delete recorded only, Delete all added

**Expected Result:**
The following sequence should be in both Vertical and Horizontal orientations:
Delete all added, Delete recorded only, Do nothing

**Comment by lwp-vinokurova** [comment]
![image](https://user-images.githubusercontent.com/85628357/126287636-f8d5e5d2-1b33-40ce-a0a4-57be133d0679.png)
![image](https://user-images.githubusercontent.com/85628357/126287652-f7a7c3ef-9146-4785-bdb4-923adcde63f6.png)

**Comment by lwp-ygavrilenko** [comment]
The current implementation utilizes default Android dialog "positive", "negative", and "neutral" options, and delegates the buttons' position handling to the platform. 
While the proposed actual result can be implemented, I don't think overriding platform behavior is justifiable in this case.
