### ISSUE TITLE
Close capture audio popup if "Clear all fields" button is pressed

### ISSUE THREAD

**Issue by lwp-vinokurova** [lwp-emelnik/musicintervals2anki#199]
### STR:
1. capture audio file (capture audio popup should still be opened)
-> captured audio file name is displayed (to be uploaded)
2. press "Clear all fields" button
-> all fields are cleared including file 
BUT file is still displayed as present in capture audio popup 

**Actual Result:** Audio file is present in capture audio popup despite all fields should be cleared 
**Expected Result:** After clear button is pressed - clear all fields and close capture audio popup

**Additional Info:** 
Close popup also if integrity check button is pressed as now it overlaps integrity check results 
Close popup when the app is closed (not collapsed, closed at all)

**Comment by lwp-vinokurova** [comment]
![image](https://user-images.githubusercontent.com/85628357/126311331-114274c2-4616-454e-8e9a-55fc0e3d6526.png)
![image](https://user-images.githubusercontent.com/85628357/126311599-22381077-8030-4c72-9492-bd154c608ac7.png)

**Comment by lwp-vinokurova** [comment]
@lwp-ygavrilenko check please, seems that popup is still displayed despite the app is closed

**Comment by lwp-ygavrilenko** [comment]
Added closing capturing overlay on closing the app. Updated back button handler to minimize the app if capturing overlay is visible.

**Comment by lwp-vinokurova** [comment]
Re-tested fix
- Popup is closed if aff is closed
