### ISSUE TITLE
Update user interface input elements

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#245]
The "Start note" group should be updated in such a way as to represent the resemblance to the piano keyboard. The "Octave" group should be updated to utilize toggle buttons instead of checkboxes. The "Interval" group should be implemented in a way similar to the "Start note" group, except that all keys should be white and the layout direction should be based on the value of the "Direction" input.
Also, the app 's button' texts should be replaced with icons where possible.

**Comment by lwp-ygavrilenko** [comment]
The filenames populating actions ("Capture audio" and "Select file") should be moved to a context menu displayed upon the new "Attach" action (that should be added).

**Comment by lwp-vinokurova** [comment]
@lwp-ygavrilenko 
Please add back the feature, that displays necessary qty of files that should be uploaded (when user selected several strat notes/intervals)

**Comment by lwp-vinokurova** [comment]
Tested:
- "Start note" group is displayed as piano keyboard 
the logic was not changed - it still works as a checkbox (check/uncheck)
- "Octave"group is displayed as buttons 
the logic was not changed - it still works as a checkbox (check/uncheck)
- "Interval" group is displayed as only white piano keyboard 
the logic was not changed - it still works as a checkbox (check/uncheck)
sequence of keys is displayed depending on direction value (ASC,DESC)
- new "Attach file" button was created
- "Capture audio" and "Select file" are moved to "Attach file" context menu
- Feature that displays necessary q-ty of files that should be uploaded is still present
- Play, Stop buttons were also changed to a new design 

All changes in design did not affect on working capacity of those features.
