### ISSUE TITLE
Code review 2021-04-28

### ISSUE THREAD

**Issue by lwp-emelnik** [lwp-emelnik/musicintervals2anki#62]
1. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L58
https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L70
Seems like these constants could/should be defined as static. The same for (some of) other final constants.
By the way, naming convention for the class constants is "uppercase with underscores" ("CHECK_NOTE_IDS" instead of "checkNoteIds").

2. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L64
https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L75
This is needed just "for programmer" to not forget to add/remove/update related values during development, right? Or there is another purpose on this?
It would be much better to use such a class initializer to populate values automatically instead of just assertion.
However, I'm not really sure that it's possible in current implementation, is it possible?

3. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L133
My IDE says that this condition is always "false", most likely something is wrong here.
Also, why such a check is performed by only "checkIntervalIds" constant? What about defined above "checkNoteIds" and "checkOctaveIds"?

4. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L153
Variable's name ("main_toolbar") does not obey the naming convention for some reason (should be "mainToolbar"). All the variables around look correct.

5. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L315
https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L736
Silent try-catch is usually a bad idea, so it makes sense to at least write some comment about why it's like that.

6. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L372
This and the next listener class definitions take up some space inside the MainActitivity class, so looks like it makes sense to move them into some separate file(s).
Not sure about some functions used there (like "findViewById") and if that would work after change or maybe should be adapted additionally (pass the label on construct etc.).

7. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L650
https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L682
https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L709
There is few places where the same complicated exception handler is used, it most likely can be simplified.
```
    } catch (MusInterval.Exception e) {
        processMusIntervalException(e);
    } catch (AnkiDroidHelper.InvalidAnkiDatabaseException e) {
        processInvalidAnkiDatabase(e);
    } catch (Throwable e) {
        processUnknownException(e);
    }
```

8. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L862
https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L1090
May produce (unhandled) 'NullPointerException'.

9. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L939
Since these literal constants used at least in two methods, it makes sense to make them class constants.

10. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MainActivity.java#L1095
Not used "res" and "msg" variables.

11. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/SettingsFragment.java#L43:
Variable "fieldPreferenceLabelStringIds" could/should be defined as final.

12. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/SettingsFragment.java#L71
It seems like there is layout definition in the code, which could be easily done in layout xml file instead.
Is there any reason to do it this way?

13. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/SettingsFragment.java#L301
May produce (unhandled) 'NullPointerException'.

14. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/SettingsFragment.java#L303
Also may be null.

15. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MusInterval.java#L132
Variable "MANDATORY" could/should be defined as final (despite the fact that it already has a naming format like constants).

16. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MusInterval.java#L148
Is there any way to put such a big (text) constants into some another file or maybe android resource (xml) and populate it from there?
It would heavily improve the readability.

17. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MusInterval.java#L499
Doen't look, but was discussed some time ago.
The same for line 1011 and AnkiDroidHelper.java:232, related issue definitely should be created (if not yet created).

18. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MusInterval.java#L550
https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MusInterval.java#L932
Looks pretty complicated and should be at least splitted into several methods.

19. https://github.com/lwp-emelnik/musicintervals2anki/blob/0ba20d0f75c5058cbd4ea5452bcb8d6d6cac15f9/app/src/main/java/com/ichi2/apisample/MusInterval.java#L744
Way more complicated logic (to be discussed).

Overall:
Sometimes I'd like to see more vertical indentation in the code, which should help readability, something like this guide may be helpful - https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace

**Comment by lwp-ygavrilenko** [comment]
1. Fixed;
2. Yes, the purpose you described is correct. The issue with automatically populating resources is that it restricts us from having different values in labels and stored fields (which is currently the case for the `interval` field);
3. This check plays the same role as the ones noted in pt. 2. For time being, I've added a comment that disables the warning for this statement. The reason this check is applied exclusively to intervals is that for notes and octaves labels directly correspond to stored values;
4. Fixed;
5. Added comments;
6. Moved field value change listeners into separate files;
7. Factored common error handler method;
8. Fixed;
9. Factored DB reference keys into static constants;
10. Fixed;
11. Fixed;
12. My reasoning for going after this approach was to save the effort of finding (retrieving) each particular component when there is a need to add additional behavior. This way the definition and initialization of settings configurators are in one place.
13. Fixed;
14. Fixed;
15. Fixed;
16. Moved default model parameters into XML resource;
17. Switched to using ArrayList instead of a regular array in conjunction with generic maps;
18. Factored common code for handling `sound_smaller` and `sound_larger` fields, moved it into a separate file;
19. Moved Integrity checking logic into a separate file & split functionality into smaller methods.
