### ISSUE TITLE
Add an option to automatically delete audio and video files upon insertion to Anki

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#86]
The function should be configured in settings, providing the following options:
- do not move any files to trash
- move to trash files created by MI2A once they processed (#24)
- move to trash both files created by MI2A and input files after they processed
- ask me next time (default)

**Comment by lwp-vinokurova** [comment]
Tested the following settings:

1. file is not deleted
2. captured file is deleted once they processed
3. uploaded files are deleted once they processed
4. ask me next time options:
- delete all added files
- delete captured files
- do not delete anything
