### ISSUE TITLE
The app displays two equal dialogs for default model creation

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#95]
Steps to reproduce:
1. Make sure the model selected in settings does not exist.  
2. Right after launching the app, press "Select file". 
If done quickly enough, a default model creation confirmation dialog will be shown, and the file chooser opened on top of it. Upon exiting the file chooser another default model creation confirmation dialog is created.

**Comment by lwp-ygavrilenko** [comment]
The easiest way to reproduce is on clean app installation: click on "Select file" right after accepting Anki's permission.

**Comment by lwp-vinokurova** [comment]
Tested:
- one dialog window is displayed in the case if on clean app installation: click on "Select file" right after accepting Anki's permission.
