### ISSUE TITLE
Trim spaces and the start and at the end of field values during integrity check

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#97]

**Comment by lwp-vinokurova** [comment]
Tested: 
- spaces are automatically trimmed in instrument field (if add from MI2A app)
- if spaces were added from AnkiDroid - they are trimmed on integrity check
- spaces are trimmed before and after instrument name
- tested case with instrument like "bass guitar" - space between words is not trimmed
