### ISSUE TITLE
Refactor audio extraction call within note adding procedure

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#98]
In #21, a call of audio extraction procedure from a video file has been added to `AnkiDroidHelper`'s `addFileToAnkiMedia` method. There is a need to implement a solution that doesn't violate the separation of concerns.

**Comment by lwp-vinokurova** [comment]
During testing the following issue was found:
- when empty file was uploaded/captured (without sound) unknown error was displayed.
music interval was not added to AnkiDroid

The following issue was fixed and re-tested.
Result: OK

Test cases:
- add video with sound - sound is extracted from the video correctly
- add video without sound - no crash 
- capture audio with sound
- capture audio without sound - no crash 
- add audio file with audio
- add audio file without sound - no crash
