### ISSUE TITLE
Fix entries order when selecting multiple files

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#99]
The order must follow the file name and modification date (ascending). If they don't match, the app should ask a user to choose either of them.
Furthermore, an option to change the order should be added to the file name list dialog.

**Comment by lwp-vinokurova** [comment]
Tested:
- if order is not "name and modification date (ascending)" -> user is asked to select sorting
- tested sorting by Name
- tested sorting by Date
-  in the file name list dialog user can select sorting again (by Name/Date)
- if order = "name and modification date (ascending)" -> user is not asked to select sorting
